
var jxl = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(jxl) {
  jxl = jxl || {};


var f;f||(f=typeof jxl !== 'undefined' ? jxl : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},f),da=[],ea="./this.program",fa=(a,b)=>{throw b;},m="",ha;m=self.location.href;_scriptDir&&(m=_scriptDir);0!==m.indexOf("blob:")?m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):m="";ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};
var ia=f.print||console.log.bind(console),r=f.printErr||console.warn.bind(console);Object.assign(f,ca);ca=null;f.arguments&&(da=f.arguments);f.thisProgram&&(ea=f.thisProgram);f.quit&&(fa=f.quit);var w;f.wasmBinary&&(w=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");var ja,ka=!1,la=new TextDecoder("utf8");function ma(a){for(var b=0;a[b]&&!(NaN<=b);)++b;return la.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))}
function na(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&B[c];)++c;return la.decode(B.subarray(a,c))}
function oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var k=a.charCodeAt(++g);l=65536+((l&1023)<<10)|k&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var qa,C,B,D,ra,E,F,sa,ta;function ua(){var a=ja.buffer;qa=a;f.HEAP8=C=new Int8Array(a);f.HEAP16=D=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAPU32=F=new Uint32Array(a);f.HEAPF32=sa=new Float32Array(a);f.HEAPF64=ta=new Float64Array(a)}var va,wa=[],xa=[],ya=[],za=[];
function Aa(){var a=f.preRun.shift();wa.unshift(a)}var G=0,Ba=null,H=null;function x(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";r(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function Ca(){return I.startsWith("data:application/octet-stream;base64,")}var I;if(f.locateFile){if(I="jxl.wasm",!Ca()){var Da=I;I=f.locateFile?f.locateFile(Da,m):m+Da}}else I=(new URL("jxl.wasm",import.meta.url)).toString();
function Ea(){var a=I;try{if(a==I&&w)return new Uint8Array(w);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}function Fa(){return w||"function"!=typeof fetch?Promise.resolve().then(function(){return Ea()}):fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ea()})}var J,Ga;
function Ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ia(a){for(;0<a.length;)a.shift()(f)}function Ja(a){this.ka=a-24;this.Va=function(b){F[this.ka+4>>2]=b};this.Ta=function(b){F[this.ka+8>>2]=b};this.Ua=function(){E[this.ka>>2]=0};this.Sa=function(){C[this.ka+12>>0]=0};this.Qa=function(){C[this.ka+13>>0]=0};this.na=function(b,c){this.Ra();this.Va(b);this.Ta(c);this.Ua();this.Sa();this.Qa()};this.Ra=function(){F[this.ka+16>>2]=0}}
var Ka=0,La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},K=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Na=
a=>{if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Oa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>x("randomDevice")}
function Pa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Qa(a,b){var c=Array(pa(a)+1);a=oa(a,c,0,c.length);b&&(c.length=a);return c}var Ra=[];function Sa(a,b){Ra[a]={input:[],$:[],oa:b};Ta(a,Ua)}
var Ua={open:function(a){var b=Ra[a.node.ua];if(!b)throw new L(43);a.Z=b;a.seekable=!1},close:function(a){a.Z.oa.ra(a.Z)},ra:function(a){a.Z.oa.ra(a.Z)},read:function(a,b,c,d){if(!a.Z||!a.Z.oa.Ia)throw new L(60);for(var e=0,g=0;g<d;g++){try{var l=a.Z.oa.Ia(a.Z)}catch(k){throw new L(29);}if(void 0===l&&0===e)throw new L(6);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Z||!a.Z.oa.za)throw new L(60);try{for(var e=0;e<d;e++)a.Z.oa.za(a.Z,
b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},Va={Ia:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Qa(b,!0)}return a.input.shift()},za:function(a,b){null===b||10===b?(ia(ma(a.$)),a.$=[]):0!=b&&a.$.push(b)},ra:function(a){a.$&&0<a.$.length&&(ia(ma(a.$)),a.$=[])}},Wa={za:function(a,
b){null===b||10===b?(r(ma(a.$)),a.$=[]):0!=b&&a.$.push(b)},ra:function(a){a.$&&0<a.$.length&&(r(ma(a.$)),a.$=[])}},M={aa:null,ea:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.aa||(M.aa={dir:{node:{ha:M.W.ha,ca:M.W.ca,pa:M.W.pa,sa:M.W.sa,Na:M.W.Na,Pa:M.W.Pa,Oa:M.W.Oa,Ma:M.W.Ma,va:M.W.va},stream:{ja:M.X.ja}},file:{node:{ha:M.W.ha,ca:M.W.ca},stream:{ja:M.X.ja,read:M.X.read,write:M.X.write,Da:M.X.Da,Ja:M.X.Ja,La:M.X.La}},
link:{node:{ha:M.W.ha,ca:M.W.ca,qa:M.W.qa},stream:{}},Ea:{node:{ha:M.W.ha,ca:M.W.ca},stream:Xa}});c=Ya(a,b,c,d);16384===(c.mode&61440)?(c.W=M.aa.dir.node,c.X=M.aa.dir.stream,c.V={}):32768===(c.mode&61440)?(c.W=M.aa.file.node,c.X=M.aa.file.stream,c.Y=0,c.V=null):40960===(c.mode&61440)?(c.W=M.aa.link.node,c.X=M.aa.link.stream):8192===(c.mode&61440)&&(c.W=M.aa.Ea.node,c.X=M.aa.Ea.stream);c.timestamp=Date.now();a&&(a.V[b]=c,a.timestamp=c.timestamp);return c},ob:function(a){return a.V?a.V.subarray?a.V.subarray(0,
a.Y):new Uint8Array(a.V):new Uint8Array(0)},Fa:function(a,b){var c=a.V?a.V.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.V,a.V=new Uint8Array(b),0<a.Y&&a.V.set(c.subarray(0,a.Y),0))},bb:function(a,b){if(a.Y!=b)if(0==b)a.V=null,a.Y=0;else{var c=a.V;a.V=new Uint8Array(b);c&&a.V.set(c.subarray(0,Math.min(b,a.Y)));a.Y=b}},W:{ha:function(a){var b={};b.nb=8192===(a.mode&61440)?a.id:1;b.qb=a.id;b.mode=a.mode;b.tb=1;b.uid=0;b.pb=0;b.ua=a.ua;16384===(a.mode&61440)?b.size=
4096:32768===(a.mode&61440)?b.size=a.Y:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.kb=new Date(a.timestamp);b.sb=new Date(a.timestamp);b.mb=new Date(a.timestamp);b.Xa=4096;b.lb=Math.ceil(b.size/b.Xa);return b},ca:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.bb(a,b.size)},pa:function(){throw Za[44];},sa:function(a,b,c,d){return M.createNode(a,b,c,d)},Na:function(a,b,c){if(16384===(a.mode&61440)){try{var d=$a(b,c)}catch(g){}if(d)for(var e in d.V)throw new L(55);
}delete a.parent.V[a.name];a.parent.timestamp=Date.now();a.name=c;b.V[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Pa:function(a,b){delete a.V[b];a.timestamp=Date.now()},Oa:function(a,b){var c=$a(a,b),d;for(d in c.V)throw new L(55);delete a.V[b];a.timestamp=Date.now()},Ma:function(a){var b=[".",".."],c;for(c in a.V)a.V.hasOwnProperty(c)&&b.push(c);return b},va:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},qa:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},
X:{read:function(a,b,c,d,e){var g=a.node.V;if(e>=a.node.Y)return 0;a=Math.min(a.node.Y-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===C.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.V||a.V.subarray)){if(g)return a.V=b.subarray(c,c+d),a.Y=d;if(0===a.Y&&0===e)return a.V=b.slice(c,c+d),a.Y=d;if(e+d<=a.Y)return a.V.set(b.subarray(c,c+d),e),d}M.Fa(a,e+d);if(a.V.subarray&&b.subarray)a.V.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.V[e+g]=b[c+g];a.Y=Math.max(a.Y,e+d);return d},ja:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Y);if(0>b)throw new L(28);return b},Da:function(a,b,c){M.Fa(a.node,b+c);a.node.Y=Math.max(a.node.Y,b+c)},Ja:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.V;if(e&2||a.buffer!==qa){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;x();b=void 0;if(!b)throw new L(48);
C.set(a,b)}else c=!1,b=a.byteOffset;return{ka:b,jb:c}},La:function(a,b,c,d){M.X.write(a,b,0,d,c,!1);return 0}}},ab=null,bb={},N=[],cb=1,db=null,eb=!0,L=null,Za={},O=(a,b={})=>{a=Pa("/",a);if(!a)return{path:"",node:null};b=Object.assign({Ha:!0,Aa:0},b);if(8<b.Aa)throw new L(32);a=La(a.split("/").filter(l=>!!l),!1);for(var c=ab,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=$a(c,a[e]);d=K(d+"/"+a[e]);c.ta&&(!g||g&&b.Ha)&&(c=c.ta.root);if(!g||b.Ga)for(g=0;40960===(c.mode&61440);)if(c=
fb(d),d=Pa(Ma(d),c),c=O(d,{Aa:b.Aa+1}).node,40<g++)throw new L(32);}return{path:d,node:c}},gb=a=>{for(var b;;){if(a===a.parent)return a=a.ea.Ka,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},hb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%db.length},$a=(a,b)=>{var c;if(c=(c=ib(a,"x"))?c:a.W.pa?0:2)throw new L(c,a);for(c=db[hb(a.id,b)];c;c=c.ab){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.W.pa(a,b)},Ya=(a,b,c,d)=>{a=new jb(a,
b,c,d);b=hb(a.parent.id,a.name);a.ab=db[b];return db[b]=a},kb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},lb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},ib=(a,b)=>{if(eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},mb=(a,b)=>{try{return $a(a,b),20}catch(c){}return ib(a,"wx")},nb=(a=0)=>{for(;4096>=a;a++)if(!N[a])return a;throw new L(33);},pb=(a,b)=>{ob||(ob=function(){this.na={}},ob.prototype=
{},Object.defineProperties(ob.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.na.flags},set:function(c){this.na.flags=c}},position:{get:function(){return this.na.position},set:function(c){this.na.position=c}}}));a=Object.assign(new ob,a);b=nb(b);a.ga=b;return N[b]=a},Xa={open:a=>{a.X=bb[a.node.ua].X;a.X.open&&a.X.open(a)},ja:()=>{throw new L(70);}},Ta=(a,b)=>{bb[a]={X:b}},qb=(a,b)=>{var c="/"===b,d=!b;if(c&&ab)throw new L(10);if(!c&&
!d){var e=O(b,{Ha:!1});b=e.path;e=e.node;if(e.ta)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,vb:{},Ka:b,$a:[]};a=a.ea(b);a.ea=b;b.root=a;c?ab=a:e&&(e.ta=b,e.ea&&e.ea.$a.push(b))},P=(a,b,c)=>{var d=O(a,{parent:!0}).node;a=Na(a);if(!a||"."===a||".."===a)throw new L(28);var e=mb(d,a);if(e)throw new L(e);if(!d.W.sa)throw new L(63);return d.W.sa(d,a,b,c)},rb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);P(a,b|8192,c)},sb=(a,b)=>{if(!Pa(a))throw new L(44);var c=O(b,{parent:!0}).node;
if(!c)throw new L(44);b=Na(b);var d=mb(c,b);if(d)throw new L(d);if(!c.W.va)throw new L(63);c.W.va(c,b,a)},fb=a=>{a=O(a).node;if(!a)throw new L(44);if(!a.W.qa)throw new L(28);return Pa(gb(a.parent),a.W.qa(a))},ub=(a,b,c)=>{if(""===a)throw new L(44);if("string"==typeof b){var d=kb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=K(a);try{e=O(a,{Ga:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&
128)throw new L(20);}else e=P(a,c,0),d=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new L(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==lb(b)||b&512)?31:ib(e,lb(b)):44))throw new L(c);if(b&512&&!d){c=e;c="string"==typeof c?O(c,{Ga:!0}).node:c;if(!c.W.ca)throw new L(63);if(16384===(c.mode&61440))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(d=ib(c,"w"))throw new L(d);c.W.ca(c,{size:0,timestamp:Date.now()})}b&=
-131713;e=pb({node:e,path:gb(e),flags:b,seekable:!0,position:0,X:e.X,ib:[],error:!1});e.X.open&&e.X.open(e);!f.logReadFiles||b&1||(tb||(tb={}),a in tb||(tb[a]=1));return e},vb=(a,b,c)=>{if(null===a.ga)throw new L(8);if(!a.seekable||!a.X.ja)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.X.ja(a,b,c);a.ib=[]},wb=()=>{L||(L=function(a,b){this.node=b;this.cb=function(c){this.ia=c};this.cb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(a=>{Za[a]=
new L(a);Za[a].stack="<generic error, no stack>"}))},xb,yb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ab=(a,b,c)=>{a=K("/dev/"+a);var d=yb(!!b,!!c);zb||(zb=64);var e=zb++<<8|0;Ta(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,l,k,n)=>{for(var q=0,u=0;u<n;u++){try{var t=b()}catch(z){throw new L(29);}if(void 0===t&&0===q)throw new L(6);if(null===t||void 0===t)break;q++;l[k+u]=t}q&&(g.node.timestamp=Date.now());return q},write:(g,l,k,n)=>{for(var q=0;q<n;q++)try{c(l[k+
q])}catch(u){throw new L(29);}n&&(g.node.timestamp=Date.now());return q}});rb(a,d,e)},zb,Q={},ob,tb,Bb=void 0;function R(){Bb+=4;return E[Bb-4>>2]}function S(a){a=N[a];if(!a)throw new L(8);return a}function Cb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Db=void 0;function T(a){for(var b="";B[a];)b+=Db[B[a++]];return b}var U={},V={},Eb={};
function Fb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Gb(a,b){a=Fb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Hb(a){var b=Error,c=Gb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ib=void 0;function W(a){throw new Ib(a);}var Jb=void 0;
function Kb(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new Jb("Mismatched type converter count");for(var n=0;n<d.length;++n)X(d[n],k[n])}var d=[];d.forEach(function(k){Eb[k]=a});var e=Array(a.length),g=[],l=0;a.forEach((k,n)=>{V.hasOwnProperty(k)?e[n]=V[k]:(g.push(k),U.hasOwnProperty(k)||(U[k]=[]),U[k].push(()=>{e[n]=V[k];++l;l===g.length&&c(e)}))});0===g.length&&c(e)}
function X(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.Ya)return;W("Cannot register type '"+d+"' twice")}V[a]=b;delete Eb[a];U.hasOwnProperty(a)&&(b=U[a],delete U[a],b.forEach(e=>e()))}var Lb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Mb(a){4<a&&0===--Y[a].Ba&&(Y[a]=void 0,Lb.push(a))}
var Nb=a=>{a||W("Cannot use deleted val. handle = "+a);return Y[a].value},Ob=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Lb.length?Lb.pop():Y.length;Y[b]={Ba:1,value:a};return b}};function Pb(a){return this.fromWireType(E[a>>2])}function Qb(a,b){switch(b){case 2:return function(c){return this.fromWireType(sa[c>>2])};case 3:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Gb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Tb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Ub(a,b){var c=f;if(void 0===c[a].ba){var d=c[a];c[a]=function(){c[a].ba.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ba+")!");return c[a].ba[arguments.length].apply(this,arguments)};c[a].ba=[];c[a].ba[d.Wa]=d}}
function Vb(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].ba&&void 0!==f[a].ba[c])&&W("Cannot register public name '"+a+"' twice"),Ub(a,a),f.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].ba[c]=b):(f[a]=b,void 0!==c&&(f[a].ub=c))}function Wb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c}var Xb=[];function Yb(a){var b=Xb[a];b||(a>=Xb.length&&(Xb.length=a+1),Xb[a]=b=va.get(a));return b}
function Zb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=f["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=Yb(b).apply(null,c);return d}}function $b(a,b){a=T(a);var c=a.includes("j")?Zb(a,b):Yb(b);"function"!=typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}var ac=void 0;function bc(a){a=cc(a);var b=T(a);Z(a);return b}
function dc(a,b){function c(g){e[g]||V[g]||(Eb[g]?Eb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new ac(a+": "+d.map(bc).join([", "]));}function ec(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var fc=new TextDecoder("utf-16le");
function gc(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&ra[c];)++c;return fc.decode(B.subarray(a,c<<1))}function hc(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function ic(a){return 2*a.length}function jc(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function kc(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function lc(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var mc={};function nc(){return"object"==typeof globalThis?globalThis:Function("return this")()}
function oc(a,b){var c=V[a];void 0===c&&W(b+" has unknown type "+bc(a));return c}
function pc(a){for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+
b+");\nreturn valueToHandle(obj);\n}\n")))(oc,f,Ob,()=>F)}var qc={},rc={};function sc(){if(!tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in rc)void 0===rc[b]?delete a[b]:a[b]=rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);tc=c}return tc}var tc;function uc(a){return 0===a%4&&(0!==a%100||0===a%400)}
var vc=[31,29,31,30,31,30,31,31,30,31,30,31],wc=[31,28,31,30,31,30,31,31,30,31,30,31];
function xc(a,b,c,d){function e(h,p,v){for(h="number"==typeof h?h.toString():h||"";h.length<p;)h=v[0]+h;return h}function g(h,p){return e(h,p,"0")}function l(h,p){function v(A){return 0>A?-1:0<A?1:0}var y;0===(y=v(h.getFullYear()-p.getFullYear()))&&0===(y=v(h.getMonth()-p.getMonth()))&&(y=v(h.getDate()-p.getDate()));return y}function k(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){var p=h.la;for(h=new Date((new Date(h.ma+1900,0,1)).getTime());0<p;){var v=h.getMonth(),y=(uc(h.getFullYear())?vc:wc)[v];if(p>y-h.getDate())p-=y-h.getDate()+1,h.setDate(1),11>v?h.setMonth(v+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+p);break}}v=new Date(h.getFullYear()+1,0,4);p=k(new Date(h.getFullYear(),
0,4));v=k(v);return 0>=l(p,h)?0>=l(v,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var q=E[d+40>>2];d={gb:E[d>>2],fb:E[d+4>>2],wa:E[d+8>>2],Ca:E[d+12>>2],xa:E[d+16>>2],ma:E[d+20>>2],da:E[d+24>>2],la:E[d+28>>2],wb:E[d+32>>2],eb:E[d+36>>2],hb:q?na(q):""};c=na(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in q)c=c.replace(new RegExp(u,"g"),q[u]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),z="January February March April May June July August September October November December".split(" ");q={"%a":function(h){return t[h.da].substring(0,3)},"%A":function(h){return t[h.da]},"%b":function(h){return z[h.xa].substring(0,3)},
"%B":function(h){return z[h.xa]},"%C":function(h){return g((h.ma+1900)/100|0,2)},"%d":function(h){return g(h.Ca,2)},"%e":function(h){return e(h.Ca,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.wa,2)},"%I":function(h){h=h.wa;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var p=0,v=0;v<=h.xa-1;p+=(uc(h.ma+1900)?vc:wc)[v++]);return g(h.Ca+p,3)},"%m":function(h){return g(h.xa+1,2)},"%M":function(h){return g(h.fb,2)},
"%n":function(){return"\n"},"%p":function(h){return 0<=h.wa&&12>h.wa?"AM":"PM"},"%S":function(h){return g(h.gb,2)},"%t":function(){return"\t"},"%u":function(h){return h.da||7},"%U":function(h){return g(Math.floor((h.la+7-h.da)/7),2)},"%V":function(h){var p=Math.floor((h.la+7-(h.da+6)%7)/7);2>=(h.da+371-h.la-2)%7&&p++;if(p)53==p&&(v=(h.da+371-h.la)%7,4==v||3==v&&uc(h.ma)||(p=1));else{p=52;var v=(h.da+7-h.la-1)%7;(4==v||5==v&&uc(h.ma%400-1))&&p++}return g(p,2)},"%w":function(h){return h.da},"%W":function(h){return g(Math.floor((h.la+
7-(h.da+6)%7)/7),2)},"%y":function(h){return(h.ma+1900).toString().substring(2)},"%Y":function(h){return h.ma+1900},"%z":function(h){h=h.eb;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.hb},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(u in q)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),q[u](d)));c=c.replace(/\0\0/g,"%");u=Qa(c,!1);if(u.length>b)return 0;C.set(u,a);return u.length-1}
function yc(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ka=!0}fa(a,new Ha(a))}function jb(a,b,c,d){a||(a=this);this.parent=a;this.ea=a.ea;this.ta=null;this.id=cb++;this.name=b;this.mode=c;this.W={};this.X={};this.ua=d}Object.defineProperties(jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});wb();db=Array(4096);qb(M,"/");
P("/tmp",16895,0);P("/home",16895,0);P("/home/web_user",16895,0);(()=>{P("/dev",16895,0);Ta(259,{read:()=>0,write:(b,c,d,e)=>e});rb("/dev/null",259);Sa(1280,Va);Sa(1536,Wa);rb("/dev/tty",1280);rb("/dev/tty1",1536);var a=Oa();Ab("random",a);Ab("urandom",a);P("/dev/shm",16895,0);P("/dev/shm/tmp",16895,0)})();
(()=>{P("/proc",16895,0);var a=P("/proc/self",16895,0);P("/proc/self/fd",16895,0);qb({ea:()=>{var b=Ya(a,"fd",16895,73);b.W={pa:(c,d)=>{var e=N[+d];if(!e)throw new L(8);c={parent:null,ea:{Ka:"fake"},W:{qa:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var zc=Array(256),Ac=0;256>Ac;++Ac)zc[Ac]=String.fromCharCode(Ac);Db=zc;Ib=f.BindingError=Hb("BindingError");Jb=f.InternalError=Hb("InternalError");
f.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};ac=f.UnboundTypeError=Hb("UnboundTypeError");
var Dc={j:function(a){return Bc(a+24)+24},i:function(a,b,c){(new Ja(a)).na(b,c);Ka++;throw a;},m:function(a,b,c){Bb=c;try{var d=S(a);switch(b){case 0:var e=R();return 0>e?-28:pb(d,e).ga;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=R(),d.flags|=e,0;case 5:return e=R(),D[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return E[Cc()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof Q||!(g instanceof L))throw g;return-g.ia}},A:function(a,b,c){Bb=c;try{var d=
S(a);switch(b){case 21509:case 21505:return d.Z?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Z?0:-59;case 21519:if(!d.Z)return-59;var e=R();return E[e>>2]=0;case 21520:return d.Z?-28:-59;case 21531:a=e=R();if(!d.X.Za)throw new L(59);return d.X.Za(d,b,a);case 21523:return d.Z?0:-59;case 21524:return d.Z?0:-59;default:return-28}}catch(g){if("undefined"==typeof Q||!(g instanceof L))throw g;return-g.ia}},B:function(a,b,c,d){Bb=d;try{b=na(b);var e=b;if("/"===e.charAt(0))b=
e;else{var g=-100===a?"/":S(a).path;if(0==e.length)throw new L(44);b=K(g+"/"+e)}var l=d?R():0;return ub(b,c,l).ga}catch(k){if("undefined"==typeof Q||!(k instanceof L))throw k;return-k.ia}},s:function(){},D:function(a,b,c,d,e){var g=Cb(c);b=T(b);X(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=C;else if(2===c)k=D;else if(4===c)k=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>
g])},fa:null})},C:function(a,b){b=T(b);X(a,{name:b,fromWireType:function(c){var d=Nb(c);Mb(c);return d},toWireType:function(c,d){return Ob(d)},argPackAdvance:8,readValueFromPointer:Pb,fa:null})},n:function(a,b,c){c=Cb(c);b=T(b);X(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:Qb(b,c),fa:null})},f:function(a,b,c,d,e,g){var l=Wb(b,c);a=T(a);e=$b(d,e);Vb(a,function(){dc("Cannot call "+a+" due to unbound types",l)},b-1);Kb(l,function(k){var n=
a,q=a;k=[k[0],null].concat(k.slice(1));var u=e,t=k.length;2>t&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var z=null!==k[1]&&!1,h=!1,p=1;p<k.length;++p)if(null!==k[p]&&void 0===k[p].fa){h=!0;break}var v="void"!==k[0].name,y="",A="";for(p=0;p<t-2;++p)y+=(0!==p?", ":"")+"arg"+p,A+=(0!==p?", ":"")+"arg"+p+"Wired";q="return function "+Fb(q)+"("+y+") {\nif (arguments.length !== "+(t-2)+") {\nthrowBindingError('function "+q+" called with ' + arguments.length + ' arguments, expected "+
(t-2)+" args!');\n}\n";h&&(q+="var destructors = [];\n");var Sb=h?"destructors":"null";y="throwBindingError invoker fn runDestructors retType classParam".split(" ");u=[W,u,g,Tb,k[0],k[1]];z&&(q+="var thisWired = classParam.toWireType("+Sb+", this);\n");for(p=0;p<t-2;++p)q+="var arg"+p+"Wired = argType"+p+".toWireType("+Sb+", arg"+p+"); // "+k[p+2].name+"\n",y.push("argType"+p),u.push(k[p+2]);z&&(A="thisWired"+(0<A.length?", ":"")+A);q+=(v?"var rv = ":"")+"invoker(fn"+(0<A.length?", ":"")+A+");\n";
if(h)q+="runDestructors(destructors);\n";else for(p=z?1:2;p<k.length;++p)t=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].fa&&(q+=t+"_dtor("+t+"); // "+k[p].name+"\n",y.push(t+"_dtor"),u.push(k[p].fa));v&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");y.push(q+"}\n");k=Rb(y).apply(null,u);p=b-1;if(!f.hasOwnProperty(n))throw new Jb("Replacing nonexistant public symbol");void 0!==f[n].ba&&void 0!==p?f[n].ba[p]=k:(f[n]=k,f[n].Wa=p);return[]})},c:function(a,b,c,d,e){b=T(b);-1===e&&(e=4294967295);
e=Cb(c);var g=k=>k;if(0===d){var l=32-8*c;g=k=>k<<l>>>l}c=b.includes("unsigned")?function(k,n){return n>>>0}:function(k,n){return n};X(a,{name:b,fromWireType:g,toWireType:c,argPackAdvance:8,readValueFromPointer:ec(b,e,0!==d),fa:null})},b:function(a,b,c){function d(g){g>>=2;var l=F;return new e(qa,l[g+1],l[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);X(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Ya:!0})},o:function(a,
b){b=T(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(d){var e=F[d>>2],g=d+4;if(c)for(var l=g,k=0;k<=e;++k){var n=g+k;if(k==e||0==B[n]){l=na(l,n-l);if(void 0===q)var q=l;else q+=String.fromCharCode(0),q+=l;l=n+1}}else{q=Array(e);for(k=0;k<e;++k)q[k]=String.fromCharCode(B[g+k]);q=q.join("")}Z(d);return q},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"==typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||
W("Cannot pass non-string to std::string");var l=c&&g?pa(e):e.length;var k=Bc(4+l+1),n=k+4;F[k>>2]=l;if(c&&g)oa(e,B,n,l+1);else if(g)for(g=0;g<l;++g){var q=e.charCodeAt(g);255<q&&(Z(n),W("String has UTF-16 code units that do not fit in 8 bits"));B[n+g]=q}else for(g=0;g<l;++g)B[n+g]=e[g];null!==d&&d.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:Pb,fa:function(d){Z(d)}})},h:function(a,b,c){c=T(c);if(2===b){var d=gc;var e=hc;var g=ic;var l=()=>ra;var k=1}else 4===b&&(d=jc,e=kc,g=lc,l=()=>
F,k=2);X(a,{name:c,fromWireType:function(n){for(var q=F[n>>2],u=l(),t,z=n+4,h=0;h<=q;++h){var p=n+4+h*b;if(h==q||0==u[p>>k])z=d(z,p-z),void 0===t?t=z:(t+=String.fromCharCode(0),t+=z),z=p+b}Z(n);return t},toWireType:function(n,q){"string"!=typeof q&&W("Cannot pass non-string to C++ string type "+c);var u=g(q),t=Bc(4+u+b);F[t>>2]=u>>k;e(q,t+4,u+b);null!==n&&n.push(Z,t);return t},argPackAdvance:8,readValueFromPointer:Pb,fa:function(n){Z(n)}})},p:function(a,b){b=T(b);X(a,{rb:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},e:Mb,d:function(a){if(0===a)return Ob(nc());var b=mc[a];a=void 0===b?T(a):b;return Ob(nc()[a])},k:function(a){4<a&&(Y[a].Ba+=1)},g:function(a,b,c,d){a=Nb(a);var e=qc[b];e||(e=pc(b),qc[b]=e);return e(a,c,d)},a:function(){x("")},x:function(a,b,c){B.copyWithin(a,b,b+c)},w:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,
d+(65536-d%65536)%65536);a:{try{ja.grow(e-qa.byteLength+65535>>>16);ua();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},u:function(a,b){var c=0;sc().forEach(function(d,e){var g=b+c;e=F[a+4*e>>2]=g;for(g=0;g<d.length;++g)C[e++>>0]=d.charCodeAt(g);C[e>>0]=0;c+=d.length+1});return 0},v:function(a,b){var c=sc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},l:function(a){try{var b=S(a);if(null===b.ga)throw new L(8);b.ya&&(b.ya=null);try{b.X.close&&b.X.close(b)}catch(c){throw c;
}finally{N[b.ga]=null}b.ga=null;return 0}catch(c){if("undefined"==typeof Q||!(c instanceof L))throw c;return c.ia}},z:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g=b=0;g<c;g++){var l=F[a>>2],k=F[a+4>>2];a+=8;var n=e,q=l,u=k,t=void 0,z=C;if(0>u||0>t)throw new L(28);if(null===n.ga)throw new L(8);if(1===(n.flags&2097155))throw new L(8);if(16384===(n.node.mode&61440))throw new L(31);if(!n.X.read)throw new L(28);var h="undefined"!=typeof t;if(!h)t=n.position;else if(!n.seekable)throw new L(70);var p=
n.X.read(n,z,q,u,t);h||(n.position+=p);var v=p;if(0>v){var y=-1;break a}b+=v;if(v<k)break}y=b}F[d>>2]=y;return 0}catch(A){if("undefined"==typeof Q||!(A instanceof L))throw A;return A.ia}},r:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=S(a);vb(g,b,d);Ga=[g.position>>>0,(J=g.position,1<=+Math.abs(J)?0<J?(Math.min(+Math.floor(J/4294967296),4294967295)|0)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[e>>2]=Ga[0];E[e+4>>2]=Ga[1];g.ya&&
0===b&&0===d&&(g.ya=null);return 0}catch(l){if("undefined"==typeof Q||!(l instanceof L))throw l;return l.ia}},y:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g=b=0;g<c;g++){var l=F[a>>2],k=F[a+4>>2];a+=8;var n=e,q=l,u=k,t=void 0,z=C;if(0>u||0>t)throw new L(28);if(null===n.ga)throw new L(8);if(0===(n.flags&2097155))throw new L(8);if(16384===(n.node.mode&61440))throw new L(31);if(!n.X.write)throw new L(28);n.seekable&&n.flags&1024&&vb(n,0,2);var h="undefined"!=typeof t;if(!h)t=n.position;else if(!n.seekable)throw new L(70);
var p=n.X.write(n,z,q,u,t,void 0);h||(n.position+=p);var v=p;if(0>v){var y=-1;break a}b+=v}y=b}F[d>>2]=y;return 0}catch(A){if("undefined"==typeof Q||!(A instanceof L))throw A;return A.ia}},t:function(a,b,c,d){return xc(a,b,c,d)},q:function(a){if(!a)return 0;E[Cc()>>2]=52;return-1}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.E;ua();va=f.asm.M;xa.unshift(f.asm.F);G--;f.monitorRunDependencies&&f.monitorRunDependencies(G);0==G&&(null!==Ba&&(clearInterval(Ba),Ba=null),H&&(e=H,H=null,e()))}function b(e){a(e.instance)}function c(e){return Fa().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){r("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:Dc};G++;f.monitorRunDependencies&&f.monitorRunDependencies(G);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){r("Module.instantiateWasm callback failed with error: "+e),ba(e)}(function(){return w||"function"!=typeof WebAssembly.instantiateStreaming||Ca()||"function"!=typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){r("wasm streaming compile failed: "+g);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.F).apply(null,arguments)};var Bc=f._malloc=function(){return(Bc=f._malloc=f.asm.G).apply(null,arguments)},Z=f._free=function(){return(Z=f._free=f.asm.H).apply(null,arguments)},Cc=f.___errno_location=function(){return(Cc=f.___errno_location=f.asm.I).apply(null,arguments)};f._main=function(){return(f._main=f.asm.J).apply(null,arguments)};var cc=f.___getTypeName=function(){return(cc=f.___getTypeName=f.asm.K).apply(null,arguments)};
f.__embind_initialize_bindings=function(){return(f.__embind_initialize_bindings=f.asm.L).apply(null,arguments)};var Ec=f.stackAlloc=function(){return(Ec=f.stackAlloc=f.asm.N).apply(null,arguments)};f.___cxa_is_pointer_type=function(){return(f.___cxa_is_pointer_type=f.asm.O).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.P).apply(null,arguments)};f.dynCall_iiji=function(){return(f.dynCall_iiji=f.asm.Q).apply(null,arguments)};
f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.R).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.S).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.T).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.U).apply(null,arguments)};var Fc;H=function Gc(){Fc||Hc();Fc||(H=Gc)};
function Ic(a){var b=f._main;a=a||[];a.unshift(ea);var c=a.length,d=Ec(4*(c+1)),e=d>>2;a.forEach(l=>{var k=E,n=e++,q=pa(l)+1,u=Ec(q);oa(l,C,u,q);k[n]=u});E[e]=0;try{var g=b(c,d);yc(g)}catch(l){l instanceof Ha||"unwind"==l||fa(1,l)}}
function Hc(){function a(){if(!Fc&&(Fc=!0,f.calledRun=!0,!ka)){f.noFSInit||xb||(xb=!0,wb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Ab("stdin",f.stdin):sb("/dev/tty","/dev/stdin"),f.stdout?Ab("stdout",null,f.stdout):sb("/dev/tty","/dev/stdout"),f.stderr?Ab("stderr",null,f.stderr):sb("/dev/tty1","/dev/stderr"),ub("/dev/stdin",0),ub("/dev/stdout",1),ub("/dev/stderr",1));eb=!1;Ia(xa);Ia(ya);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Jc&&Ic(b);if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();za.unshift(c)}Ia(za)}}var b=b||da;if(!(0<G)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();Ia(wa);0<G||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Jc=!1;f.noInitialRun&&(Jc=!1);Hc();


  return jxl.ready
}
);
})();
export default jxl;